base_url = "https://semanticdata.github.io/selva/"
compile_sass = true
build_search_index = false
generate_feeds = true

[markdown]
highlight_code = true

[extra]
# Put all your custom variables here
